name: RDP setup on ubuntu
# on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Google Chrome on your computer.
        run: |
        sudo apt-get update
        sudo apt-get install xfce4 -y
        sudo apt-get install desktop-base -y
        sudo apt-get install task-xfce-desktop -y
        sudo apt-get install xscreensaver -y
        sudo echo "exec /etc/X11/Xsession /usr/bin/xfce4-session" >>/etc/chrome-remote-desktop-session
        sudo curl https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb -o /tmp/chrome-remote-desktop_current_amd64.deb
        sudo dpkg --install /tmp/chrome-remote-desktop_current_amd64.deb
        sudo rm -f /tmp/chrome-remote-desktop_current_amd64.deb
        sudo curl https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o /tmp/google-chrome-stable_current_amd64.deb
        sudo rm -f /tmp/google-chrome-stable_current_amd64.deb
        sudo apt-get install -f -y
        sudo systemctl stop lightdm
